#
import pandas as pd
from os.path import join

configfile: 'config/config.yml'

#load participants.tsv file, and strip off sub- from participant_id column
df = pd.read_table(config['participants_tsv'])
subjects = df.participant_id.to_list() 
subjects = [ s.strip('sub-') for s in subjects ]

hemis = 'lh rh'.split()

#needed since std meshes sometimes use L/R instead of lh/rh
hemi_to_H = dict({'lh': 'L', 'rh': 'R'})
H_to_hemi = dict({'L': 'lh', 'R': 'rh'})

#get list of ROIs
if config['lhrh_targets_independent_condition']:
    f = open(config['targets_txt_lh-rh_separate_358regions'],'r')
    targets = [line.strip() for line in f.readlines()]
    f.close()
else:
    f = open(config['targets_txt_lh-rh_combined_179regions'],'r')
    targets = [line.strip() for line in f.readlines()]
    f.close() 

#get seeds, as keys in template_prob_seg
seeds = config['template_prob_seg'].keys()


#bids-naming for subject and template (only alphanumeric characters)
wildcard_constraints:
    subject="[a-zA-Z0-9]+",
    template="[a-zA-Z0-9]+",
    seed="[a-zA-Z0-9]+",
    surfname='white|pial|sphere.reg',
    volname='T1',
    target="[a-zA-Z0-9]+"

localrules: all

#include: 'rules/hcp7T_Diffusion_bedpostx_gpu.smk'

include: 'rules/hcp_mmp.smk'

include: 'rules/diffparc.smk'

#include: 'rules/tractmap.smk'



#If want to run everything including tractmap, uncomment everything and this rule all
#rule all:
#    input: 
#        outdseg = expand('results/tractmap/transform_tractmaps_to_template/templateSpace-{template}_{seed}_k-{k}_tractmaps_Averaged_dseg_FINAL.nii.gz',template=config['template'],seed=seeds,k=range(2,config['max_k']+1))
#        Gephi_Nodes_and_Edges_Tables_dir = 'results/gephi_input_NodesandEdges_tables'


#If want to run only bedpostx_gpu, uncomment this and only uncomment rules/hcp7T_Diffusion_bedpostx_gpu.smk
#rule all:
#    input: expand('results/Diffusion_7T/{subject}.bedpostX/mean_S0samples.nii.gz',subject=subjects)


#If want to run only hcp_mmp and diffparc after running bedpost, uncomment this and only uncomment rules/hcp_mmp.smk and rules/diffparc.smk, and use snakemake --profile cc-slurm --until gen_targets_txt
rule all:
    input:
        clusters_k = expand('results/clustering/group_space-{template}_seed-{seed}_method-spectralcosine_k-{k}_cluslabels.nii.gz', template=config['template'],seed=seeds,k=range(2,config['max_k']+1)),
	Gephi_Nodes_and_Edges_Tables_dir = expand('results/gephi_input_NodesandEdges_tables_{seed}',seed=seeds)
